// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Assignment struct {
	Course    *Course    `json:"course"`
	Prof      *Professor `json:"prof"`
	StartDate *string    `json:"startDate"`
	EndDate   *string    `json:"endDate"`
	BeginTime *string    `json:"beginTime"`
	EndTime   *string    `json:"endTime"`
	Sunday    *bool      `json:"sunday"`
	Monday    *bool      `json:"monday"`
	Tuesday   *bool      `json:"tuesday"`
	Wednesday *bool      `json:"wednesday"`
	Thursday  *bool      `json:"thursday"`
	Friday    *bool      `json:"friday"`
	Saturday  *bool      `json:"saturday"`
}

type Course struct {
	CourseNumber   *int    `json:"courseNumber"`
	Subject        *string `json:"subject"`
	SequenceNumber *string `json:"sequenceNumber"`
	CourseTitle    *string `json:"courseTitle"`
}

type NewCourse struct {
	CourseNumber   *int    `json:"courseNumber"`
	Subject        *string `json:"subject"`
	SequenceNumber *string `json:"sequenceNumber"`
	CourseTitle    *string `json:"courseTitle"`
}

type NewProfessor struct {
	DisplayName *string `json:"displayName"`
}

type Professor struct {
	DisplayName *string `json:"displayName"`
}

type Schedule struct {
	Assignments []*Assignment `json:"assignments"`
}
